### ISSUE TITLE
removal of doubles

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/c14bazAAR#5]
[c14bazAAR/R/c14_date_list_rm_doubles.R](https://github.com/ISAAKiel/c14bazAAR/blob/master/R/c14_date_list_rm_doubles.R)

**How it works right now:**
1. For all dates search for the dates which contain the same labnr string within their labnr string.
2. Reduce selection of dates to those, who could be doubles based on the result of 1..
3. For all remaining dates create a data.frame with all the info of the partner doubles (data.frames in data.frame).
4. Define a set of essential variables. 
5. Decision process:
    1. If all partner doubles are exactly equal in all variables, keep one and throw the rest away.
    2. If the labnr is exactly equal, throw away the ones which lack more info in the essential variables. If they lack the same amount of info here, then also look at the non-essential variables. If no differences here either, than just keep the first date and throw the rest away.
   3. If the labnr is not exactly equal, then just keep the dates.
6. Execute the selection.

There's an option to only mark doubles that should be removed in an extra column without executing the removal.

I worked with [list columns](https://jennybc.github.io/purrr-tutorial/ls13_list-columns.html) here. Can be confusing at the first (and the second) moment. 

**Questions:**
- Is the criterion (labcode) to identify doubles sufficient?
- How to decide which doubles to remove? Priority of certain essential variables? 
- Can it be done faster?

**Comment by FFaupel** [comment]
How we would like to improve the existing removal:
![rm_doubles01](https://user-images.githubusercontent.com/17333068/33264141-a33165f6-d36c-11e7-9c67-cd3e4bdfdc1f.jpg)
![rm_doubles02](https://user-images.githubusercontent.com/17333068/33264144-a51ce2e6-d36c-11e7-9c5e-368264d42004.jpg)

**Comment by nevrome** [comment]
If I get this approach correctly, then you just want to let the user make a manual decision via `edit()` or an other GUI tool. No automatic selection criteria. 

I don't think this is a good solution in the context of the c14bazAAR: 

1. c14bazAAR is intended to be used as a **fast** query and selection engine. It should provide tools to give you an **overview** without spending a lot of time for data preparation. Imagine the user has to make hundreds of double removal decisions before he gets a first clean map with the actual amount of dates for his research question... Please keep in mind that c14bazAAR will also be the backend of [neolithicrc](https://www.forschungsdatenarchiv.escience.uni-tuebingen.de/cSchmid/neolithicRC/). 

2. c14bazAAR shouldn't require the user to already know what he's searching for. Maybe **he has no idea** which dates to keep and to remove at this stage of his research process.

3. Data **filtering should be scripted** to ensure documentation and reproducibility. At one point the user will have to make manual decisions about what dates he wants to exclude for his research. But we shouldn't provide him with GUI tools to do this (or for anything beyond temporary operations). Reproducible research means that there's a script for data manipulation.

What you're suggesting so far is to remove the algorithm completely and replace it with human labor. That's not what I had in mind ;-)...

**Comment by nevrome** [comment]
Ideas:
- function A: Mark doubles. Factor field with "duplicate groups".
- function B: Show doubles (!).  Maybe list of double pairs.
- function C: Remove simple (!) doubles.
- function D: Powermerging -> Combine info from doubles into one date. With force!

In neolithicRC:
- only function A and color coding in table + text info ("In this selection you have X duplicates.")
- unrelated: code generator for neolithicRC
