### ISSUE TITLE
Remove duplicates does not find duplicates

### ISSUE THREAD

**Issue by nmueller18** [ISAAKiel/c14bazAAR#60]
In a query of mine, the `remove duplicate`-function does not work as expected. It seems that duplicates between RADON und EUROEVOL are not found, seemingly because the latter does not use hyphens in the laboratory code (e.g. "Gd 6046" vs. "Gd-6046")

**Comment by nevrome** [comment]
Good observation! Thank you!

It's not surprising given that the comparison algorithm is purposely [simple](https://github.com/ISAAKiel/c14bazAAR/blob/62b2174d8b6d84baacd95ccb30d8d7753a5ada98/R/c14_date_list_duplicates_mark.R#L83). Maybe we could change the way EUROEVOL is loaded to add the hyphens? What do you think?

**Comment by nmueller18** [comment]
Grrr. I had a look at the original EUROEVOL-dataset, and it is not consistent even there: Sometimes there are hyphens, sometimes there are spaces and sometimes neither. I think a parsing line (with catering for the three cases) should be entered here: `c14age = .data[["C14Age"]],`

**Comment by nmueller18** [comment]
Are you sure that you have pushed your changes? I can see no differences.

**Comment by nevrome** [comment]
The changes are only in the specific branch for this issue.

You can install the version with them with `devtools::install_github("ISAAKiel/c14bazAAR#61")`

**Comment by nmueller18** [comment]
Okay, I did not realize you created a new branch.

Indeed, there is an unexpected result: Some CALPAL-dates now have two hypens (e.g. `UtC--10808`). I suspect an ASCII-character that only looks like a hyphen.

**Comment by nevrome** [comment]
The CalPal dates already had the double hyphens. I defined another case to solve this.

**Comment by nmueller18** [comment]
Another case: Duplicate entries in the same database (RADON):

> KN-1531
> KN-I.531

**Comment by nevrome** [comment]
I don't think we can capture errors like this automatically. Or is there a systematic (!) difference that applies to many date pairs?

For individual errors: Please contact the authors of RADON.

**Comment by nmueller18** [comment]
I think you can merge this branch. At least for me it works as expected and produced no detrimental results.
