### ISSUE TITLE
Merging duplicates leads to NAs

### ISSUE THREAD

**Issue by nmueller18** [ISAAKiel/c14bazAAR#62]
In the process of merging duplicates, it seems that in some instances NAs in the column `lon` are produced. The following should reproduce an example dataset:

> x <- get_all_dates()
> x_material <- x %>% classify_material()
> x_country <- x_material %>%
> 	standardize_country_name() %>%
> 	determine_country_by_coordinate() %>%
> 	finalize_country_name()
> x_duplicate <- x_country %>%
> 	mark_duplicates() %>%
> 	remove_duplicates()
> x_sub<-x_duplicate[grepl("Viesen", x_duplicate$site),]

I found out because I was subsetting the data by coordinates and was surprised not finding those from the Viesenhäuser Hof.

**Comment by nevrome** [comment]
I believe this expected behaviour. In the documentation of `remove_duplicates()` I wrote the following paragraph:

> c14bazAAR::remove_duplicates() removes them by merging all dates in a duplicate_group. All non-equal variables in the duplicate group are turned to NA. A new column duplicate_remove_log documents the variety of entries initially provided (and partially lost by this hard merging operation).

If the different databases do not agree, than the value is replaced by NA.

**Comment by nmueller18** [comment]
This seems like a good option to me, because otherwise you might be forced to look up crucial information in the column `duplicate_remove_log`.

**Comment by nevrome** [comment]
I will implement this feature when I have some free time.

Until then you could merge the info from the preferred database back into your compilation.

**Comment by nmueller18** [comment]
I think this is urgent. At the moment, the most common dates (= present in more than one database) are the least likely to be included when subsetting the results, e. g. by culture. "Linienbandkeramik" in one database and "Linearbandkeramik" in the other will produce "NA" in the merged table and thus will not be included in the subset.

**Comment by nevrome** [comment]
@nmueller18 Would you mind testing #63? The new feature is documented in `?duplicates`. 

I know that there are some other issues with deprecated functions and a reading error for one source database. You can ignore these and focus on the functionality of the new `preferences` option of `remove_duplicates()`.

**Comment by nevrome** [comment]
#63 added some better solutions for the deduplication problem.
