### ISSUE TITLE
rOpenSci Review: Package preparation ToDo

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/c14bazAAR#70]
c14bazAAR should follow the rOpenSci [Packaging Guide](https://devguide.ropensci.org/building.html#building). This guide recommends some useful changes to the package, but also a lot of optional stuff that I don't think is really necessary or even desirable.

So here are the things that I think should be changed and that I didn't already do:

- [x] 1.9 Authorship: *The DESCRIPTION file of a package should list package authors and contributors to a package, using the Authors@R syntax to indicate their roles (author/creator/contributor etc.) if there is more than one author, and using the comment field to indicate the ORCID ID of each author, if they have one*. Could you change the Description file accordingly, @MartinHinz? Please do not forget to document this change in NEWS.md.

- [x] 1.10 Testing: We have good coverage, but some of the new stuff is not covered yet. Could you write some tests for the new `remove_duplicates` options that I recently added in this epic PR, @dirkseidensticker?

***

Here are some recommended/suggested things that I do not want to do, because I think they are not useful and/or work intensive in the long run. What do you think?

- 1.1.2 Creating metadata for your package: *We recommend you to use the codemetar package for creating and updating a JSON CodeMeta metadata file for your package via codemetar::write_codemeta().*

- 1.5 Code Style: *We recommend the styler package for automating part of the code styling.*

- 1.6 README: *We recommend not creating README.md directly, but from a README.Rmd file.*

- 1.7 Documentation: *The package should contain at least one vignette providing a substantial coverage of package functions, illustrating realistic use cases and how functions are intended to interact. If the package is small, the vignette and the README can have the same content.* I disagree, but I am afraid that I will have to give in on this one. 

- 1.8 Documentation website: *We recommend creating a documentation website for your package using pkgdown.*

**Comment by MartinHinz** [comment]
updated DESCRIPTION and NEWS.md according to 1.9
