### ISSUE TITLE
rOpenSci Review: JOSS Submission ToDo

### ISSUE THREAD

**Issue by nevrome** [ISAAKiel/c14bazAAR#71]
There's a possibility to submit a very short, descriptive paper about c14bazAAR to the [Journal of Open Source Software](http://joss.theoj.org/) with the review. I want to do that. 

- [x] The package therefore has to contain a `paper.md` file with the text in the package root. Structure and content of this file are described [here](https://joss.readthedocs.io/en/latest/submitting.html).
- [x] The package has to be deposited in a long-term repository with a DOI.

**Comment by nevrome** [comment]
@MartinHinz, @dirkseidensticker: Please take a look at the current version of the `paper.md`. I prepared a very first draft of the text.

**Comment by MartinHinz** [comment]
Made some suggestions for changes in b280ede.
